### ISSUE TITLE
Write up something explaining how others can create plugins?

### ISSUE THREAD

**Issue by jgeewax** [jgeewax/phoenix#41]
Hey @callmehiphop 

Can we put together a readme of sorts that explains how someone new would get bootstrapped and able to start building plugins?

@bokowski wants to poke around and needs a bit of guidance.

**Comment by callmehiphop** [comment]
Absolutely! Do we have any interest in a very simple yeoman generator for plugins at this time?

**Comment by jgeewax** [comment]
A generator would be great, but not really the priority for now... So for
starters how about we get something that explains everything to newcomers
and then go from there ?

**Comment by callmehiphop** [comment]
Sounds good
